### ISSUE TITLE
Database connection issue on first install

### ISSUE THREAD

**Issue by kellyatkinson** [PJ1004/ianseo#2]
With a vanilla fresh install, with the only change being the host port, I still can't get the installation to complete successfully with the 'db' database name:

![image](https://github.com/PJ1004/ianseo/assets/8167044/4f3ab9b6-7a16-44e5-9a62-ca8a8f98ada5)

Suggest we figure this out together and tweak instructions to suit.

**Comment by PJ1004** [comment]
Hi there - the `database name` is `ianseo`.  Try replacing the `127.0.0.1` with `db` instead.

**Comment by kellyatkinson** [comment]
Success! Thanks!
